### ISSUE TITLE
Questions related to go application and distroless image

### ISSUE THREAD

**Issue by shounak1** [Parag-S-Salunkhe/go-application-devops#1]
I can just see that you mentioned how to run the application by running `go run main.go`. But I did not understand the purpose of this application.

1. You mentioned that you made the application distro less. Could you explain how it helps?
2. If you are using github actions, I cannot see the `.github` directory which contains the pipelines that need to be run. For example check out [this](https://github.com/ad-m/github-push-action/tree/master) repo which makes use of github actions.
3. You mentioned that you are using Helm charts. Is there a separate repository for helm charts?
4. You mentioned Ingress but I do not see the manifest for ingress.

**Comment by Parag-S-Salunkhe** [comment]
I have not developed this application. My motive of this project was to do implementation of DevOps side. its a simple stateless web application.

1.  you can see in the below image there are images with tag 'v1' and 'test' - the 'test' image is a containerized image with just 1 stage and is of size 900 mb , 'v1' is multi stage containersation which takes only 30 mb (both images are compressed to half of it in docker hub, this screenshot is of docker desktop).  
![multi-stage-docker](https://github.com/user-attachments/assets/1b1d82e5-71eb-49cf-bddf-e5112fb4e625)

What is distroless image? - it is a minimal docker image with only essential components needed to run the application, without an entire application system, unnecessary tools and libraries.

how does it help ? - it makes our container more safe (enhances security) as there is no package manager or shell, so it cant be easily modified or used for debugging. only containes the required runtime environment required for running the application.
AND in the case of a go application there is no runtime environment like java with JVM or python with python interpretor. 

how do you choose a distroless image for your application? - any distroless image are tailored for specific languages , choose one which matches the language of your application. Make sure the image has necessary runtime dependencies and a good community and maintenance.

2- 3- 4- : the project was ongoing when you had commented , all the files are available now. will be updating the readme and updating documentation
